service: aws-pdf-generator
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  profile: yoelvismulen

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
  startSF:
    handler: handler.startSF
    events:
      - httpApi:
          path: /startSF
          method: POST

plugins:
  - serverless-step-functions
  - serverless-step-functions-local
  - serverless-offline-lambda
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3500
  stepFunctionsLocal:
    accountId: 101010101010
    region: us-east-1
    TaskResourceMapping:
      FirstState: arn:aws:lambda:us-east-1:101010101010:function:hello

stepFunctions:
  stateMachines:
    HelloMachine:
      definition:
        Comment: "An example of the Amazon States Language"
        StartAt: HelloState
        States:
          HelloState:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            End: true
